---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/cds_grid1/cds_grid1.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/4990/articles/297556/master/file/figures/cds_grid1/cds_grid1.png"
