---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/pse_heatmaps/pse_heatmaps.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/4990/articles/297556/master/file/figures/pse_heatmaps/pse_heatmaps.png"
    folder_url: "/users/4990/articles/297556/master/folder/figures/pse_heatmaps"
