---
version: 2
multicolumn: false
web-width: 500
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/JohnGriffiths_Esig/cross_section_test.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/4990/articles/297556/master/folder/figures/JohnGriffiths_Esig"
    url: "/users/4990/articles/297556/master/file/figures/JohnGriffiths_Esig/cross_section_test.png"
